name: Download File

on:
  repository_dispatch:
    types: [email_file]

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download File
        run: |
          mkdir -p uploads
          curl -L "${{ github.event.client_payload.file_url }}" \
          -o uploads/downloaded_file

      - name: Commit File
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add uploads/
          git commit -m "Auto upload from email" || exit 0
          git push
