name: Download File

on:
  repository_dispatch:
    types: [email_file]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Workflow Started
        run: |
          echo "Hello Aditya"
          echo "Workflow triggered successfully"
