name: Download File

on:
  repository_dispatch:
    types: [email_file]

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create folder
        run: mkdir -p downloaded_files

      - name: Save URL
        run: |
          echo "${{ github.event.client_payload.url }}" > downloaded_files/latest_download_link.txt

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add downloaded_files/latest_download_link.txt

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update download link"
          git push
